parameters:
    locale: 'en'
    device_storage_path_map:
        front-left: '%env(FRONT_LEFT_STORAGE_PATH)%'
        front-right: '%env(FRONT_RIGHT_STORAGE_PATH)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Controller\NotificationController:
        bind:
            $paginator: '@knp_paginator'

    App\EventListener\NotificationSubscriber:
        tags:
            - { name: doctrine.orm.entity_listener, event: postLoad, entity: App\Entity\Notification }
